### ISSUE TITLE
fix sanity testing issues

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#139]
I've added a dedicated build step for sanity testing, which is coming back with a handful of issues. This will help us with upstream acceptance.

Can we step through these and validate what needs to be fixed, and fix it?

You can see the log here: https://travis-ci.com/nutanix/terraform-provider-nutanix

And also access this via make sanity locally

**Comment by Crizstian** [comment]
Hello @JonKohler i have been fixing the sanity issues, but rhere some checks that are irrelevant like this ones:
```
nutanix/data_source_nutanix_image.go:59:7: Error return value of `d.Set` is not checked (errcheck)
	d.Set("cluster_reference_name", cl)
```

There is no need to check an error for simple setters, only for complex setters is where are required to check if an error happens, otherwise if i add all the error checks for simple setters, the gocycle will increment,  so i will leave the decision to you, if you want me to set all the error checking and increment the gogcycle check or should i leave it simple, in my opinion i will leave it simple as it is right now.

**Comment by JonKohler** [comment]
@cgriggs01 - What does hashicorp recommend for errcheck failures like this?

**Comment by JonKohler** [comment]
@cgriggs01 ?

**Comment by JonKohler** [comment]
bump @cgriggs01, we'd love to keep up the drum beat here

**Comment by thetonymaster** [comment]
@JonKohler let me summon him

**Comment by cgriggs01** [comment]
Hey @JonKohler, sorry for leaving you hangin'. 

Let me check with the Terraform team to get their opintion. We don't have this docuemented yet so its hard to say without diving into similar tests in other providers.

**Comment by JonKohler** [comment]
ok thanks @cgriggs01 - and to be clear, this is flagging from errcheck, which is the standard errcheck that everyone runs if I recall correctly.

**Comment by JonKohler** [comment]
@cgriggs01  - did you hear back?

**Comment by JonKohler** [comment]
I'm going to close this out as I never heard back from @cgriggs01 about this. Will bring this up when we go through terraform engineering code review
