### ISSUE TITLE
Change VM caused disk being deleted

### ISSUE THREAD

**Issue by pjgunadi** [nutanix/terraform-provider-nutanix#220]
**Describe the bug**
When applying VM change of CPU / RAM / Description, the disks of the VM are deleted

**Expected behavior**
Change CPU/RAM/Description should not delete the disks.

**Logs**
<img width="311" alt="screenshot 2019-02-10 at 10 53 33 pm" src="https://user-images.githubusercontent.com/10342114/52535241-dbeb2880-2d86-11e9-9672-b1fedcfde676.png">

**Versions (please complete the following information):**
 - OS that is executing Terraform: tried in Ubuntu and MacOS
 - Terraform v0.11.11
 - Nutanix Cluster: Prism Element: 5.9.2
 - Nutanix Prism Central: Version 5.9.2
 - Terraform provider version: v1.0.0 and github develop branch commit id ad11ad0

**Comment by JonKohler** [comment]
The prism central version you listed looks like the AHV version, not the prism central version or prism element version.

Can you go into prism, click the menu in the top right hand corner, click about, and give the version for both prism central and prism element? Should be something like 5.9, 5.10, etc

Jon Kohler, VCDX, NPX
Technical Director, Nutanix Engineering

Sent from my iPhone

On Feb 10, 2019, at 10:05 AM, pjgunadi <notifications@github.com<mailto:notifications@github.com>> wrote:


Describe the bug
When applying VM change of CPU / RAM / Description, the disks of the VM are deleted

Expected behavior
Change CPU/RAM/Description should not delete the disks.

Logs
[screenshot 2019-02-10 at 10 53 33 pm] [user-images.githubusercontent.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_10342114_52535241-2Ddbeb2880-2D2d86-2D11e9-2D9672-2Db1fedcfde676.png&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=NGPRGGo37mQiSXgHKm5rCQ&m=2oH1iJPGNg4mPTa4K0isSpaRvAesCn5Bfp_m3qpp9jc&s=kg6pner0mDkdKuaKcCp5VKDrhcTZ2PQxQanhEw5MISs&e=>

Versions (please complete the following information):

  *   OS that is executing Terraform: tried in Ubuntu and MacOS
  *   Terraform v0.11.11
  *   Nutanix Cluster: Prism
  *   Nutanix Prism Central: 20170830.184
  *   Terraform provider version: v1.0.0 and github develop branch commit id ad11ad0 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nutanix_terraform-2Dprovider-2Dnutanix_commit_ad11ad0db56e0f2a54a03d658e6c7c7b7fc42381&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=NGPRGGo37mQiSXgHKm5rCQ&m=2oH1iJPGNg4mPTa4K0isSpaRvAesCn5Bfp_m3qpp9jc&s=sL268dvA01g03GxsNHdpYu12HasZcsr3w8LEVd5aFjY&e=>

**Comment by pjgunadi** [comment]
Versions shown from 'About Nutanix':
Version euphrates-5.9.2-stable
NCC Version: 3.6.2.1
LCM Version: 2.1.3578

**Comment by JonKohler** [comment]
If its the same issue I'm thinking of, you'd need to jump up past 5.10 to get the fix from PC and PE level. 5.10.1 is the latest code, 5.10.2 is right around the corner

**Comment by timboothby** [comment]
Hi Jon,
Can you elaborate on this a little. I'm playing with Terraform on our lab running CE 2018.05.17 and am seeing the same issue, changes to VMs in the tf config cause the VM's drives to be deleted.
It sounds like you are saying this is a bug in PC/PE? Is there a release date for a 5.10.X build of CE?
Cheers,
Tim

**Comment by JonKohler** [comment]
For sure that version of CE will not have the coe that I'm talking about. I have a strong feeling it IS this bug I was referring too, but haven't had a chance to confirm. If anyone else can test it thru a 5.10.x build, we should be able to confirm.

WRT CE - I dont know what the current release schedule looks like for that offhand, would be worth pinging the user forums on that if you haven't already

**Comment by JonKohler** [comment]
I moved this issue to the upstream repo, here: https://github.com/terraform-providers/terraform-provider-nutanix/issues/34
