### ISSUE TITLE
nutanix_volume_group resource not supported

### ISSUE THREAD

**Issue by pjgunadi** [nutanix/terraform-provider-nutanix#221]
**Describe the bug**
Create resource_volume_group error: "Provider doesn't support resource: nutanix_volume_group"

**Expected behavior**
https://www.terraform.io/docs/providers/nutanix/index.html shows nutanix_volume_group is in resources list 

**Logs**
"Provider doesn't support resource: nutanix_volume_group"

**Versions (please complete the following information):**
 - OS that is executing Terraform: MacOS
 - Terraform v0.11.11
 - Nutanix Cluster (Prism Element / AOS): 5.9
 - Nutanix Prism Central
 - Terraform provider version v.1.0.0

**Comment by JonKohler** [comment]
This is expected. There is another GH issue already tracking this. Long story short the prism central API for volume groups isn’t where it needs to be, so technically we could have gotten it to work on prism element, and shipped it, but I personally wasn’t comfortable with having that difference, so I told the team to pull this.

Obviously we missed the documentation during the pull, so we’ll need to fix that to prevent confusion.

Thank you for reporting this, I appreciate the attention to detail from you.

Cheers
Jon

Jon Kohler, VCDX, NPX
Technical Director, Nutanix Engineering

Sent from my iPhone

On Feb 11, 2019, at 3:28 AM, pjgunadi <notifications@github.com<mailto:notifications@github.com>> wrote:


Describe the bug
Create resource_volume_group error: "Provider doesn't support resource: nutanix_volume_group"

Expected behavior
https://www.terraform.io/docs/providers/nutanix/index.html [terraform.io]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.terraform.io_docs_providers_nutanix_index.html&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=NGPRGGo37mQiSXgHKm5rCQ&m=-hsW8pFapUiVR6upWYkm0Uo1OWRVQpdqhdA533Wwyj4&s=pMqtn_tx06bRizzssA8Iq1Hca16DynY44qk7JOoVTmU&e=> shows nutanix_volume_group is in resources list

Logs
"Provider doesn't support resource: nutanix_volume_group"

Versions (please complete the following information):

  *   OS that is executing Terraform: MacOS
  *   Terraform v0.11.11
  *   Nutanix Cluster (Prism Element / AOS): 5.9
  *   Nutanix Prism Central
  *   Terraform provider version v.1.0.0

**Comment by JonKohler** [comment]
This issue is being tracked in the upstream repo, here: https://github.com/terraform-providers/terraform-provider-nutanix/issues/15
