### ISSUE TITLE
Implement Timeout blocks on resource level

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/terraform-provider-nutanix#254]
**Is your feature request related to a problem? Please describe.**
Currently the wait_timeout attribute works on a provider level. An enhancement would be to put this functionality on a per resource basis

**Describe the solution you'd like**
Implement functionality like mentioned here:
https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts

**Describe alternatives you've considered**
None

**Comment by marinsalinas** [comment]
Hey @yannickstruyf3, we are aware of the resource level CRUD operations timeout, the resource why we added as a provider level is because at that time the Terraform provider development documentation is wasn't very clear on how to manage those timeout, so we decided to add it at provider level (global).


Here is more context about the initial implementation:
https://github.com/nutanix/terraform-provider-nutanix/issues/20
https://github.com/nutanix/terraform-provider-nutanix/pull/42

So we can add it as a feature in a future version of this provider.
